// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="or_gate_or_gate,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-ftg256-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.508000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=26,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module or_gate (
        a,
        b,
        c,
        ap_rst
);


input  [0:0] a;
input  [0:0] b;
output  [0:0] c;
input   ap_rst;

wire   [1:0] b_cast_fu_63_p1;
wire   [1:0] a_cast_fu_59_p1;
wire   [1:0] tmp2_fu_67_p2;
wire   [5:0] tmp1_fu_73_p3;
wire   [5:0] z_fu_81_p2;
wire   [0:0] tmp_fu_87_p3;

assign a_cast_fu_59_p1 = a;

assign b_cast_fu_63_p1 = b;

assign tmp1_fu_73_p3 = {{tmp2_fu_67_p2}, {4'd0}};

assign tmp2_fu_67_p2 = (b_cast_fu_63_p1 + a_cast_fu_59_p1);

assign tmp_fu_87_p3 = z_fu_81_p2[32'd5];

assign z_fu_81_p2 = ($signed(tmp1_fu_73_p3) + $signed(6'd56));

assign c = (tmp_fu_87_p3 ^ 1'd1);

endmodule //or_gate
