// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="nand_gate_nand_gate,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-ftg256-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.345857,HLS_SYN_LAT=164,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=100,HLS_SYN_LUT=398,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module nand_gate (
        ap_clk,
        ap_rst,
        a,
        b,
        c,
        w1_out,
        w2_out,
        bias_out
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input  [0:0] a;
input  [0:0] b;
output  [0:0] c;
output  [7:0] w1_out;
output  [7:0] w2_out;
output  [7:0] bias_out;

wire    grp_nand_gate_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_35_2_fu_102_ap_start;
wire    grp_nand_gate_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_35_2_fu_102_ap_done;
wire    grp_nand_gate_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_35_2_fu_102_ap_idle;
wire    grp_nand_gate_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_35_2_fu_102_ap_ready;
wire   [7:0] grp_nand_gate_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_35_2_fu_102_w1_out;
wire    grp_nand_gate_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_35_2_fu_102_w1_out_ap_vld;
wire   [7:0] grp_nand_gate_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_35_2_fu_102_w2_out;
wire    grp_nand_gate_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_35_2_fu_102_w2_out_ap_vld;
wire   [7:0] grp_nand_gate_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_35_2_fu_102_bias_out;
wire    grp_nand_gate_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_35_2_fu_102_bias_out_ap_vld;
reg    grp_nand_gate_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_35_2_fu_102_ap_start_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [7:0] w1_loc_fu_58;
wire    ap_CS_fsm_state2;
reg   [7:0] w2_loc_fu_54;
reg   [7:0] bias_loc_fu_50;
wire    ap_CS_fsm_state3;
wire   [7:0] select_ln63_fu_121_p3;
wire   [7:0] select_ln63_1_fu_135_p3;
wire   [7:0] and_ln63_fu_129_p2;
wire   [7:0] add_ln63_fu_149_p2;
wire   [7:0] and_ln63_1_fu_143_p2;
wire   [7:0] z_final_fu_155_p2;
wire   [0:0] tmp_fu_161_p3;
reg   [2:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 grp_nand_gate_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_35_2_fu_102_ap_start_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
end

nand_gate_nand_gate_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_35_2 grp_nand_gate_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_35_2_fu_102(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_nand_gate_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_35_2_fu_102_ap_start),
    .ap_done(grp_nand_gate_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_35_2_fu_102_ap_done),
    .ap_idle(grp_nand_gate_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_35_2_fu_102_ap_idle),
    .ap_ready(grp_nand_gate_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_35_2_fu_102_ap_ready),
    .w1_out(grp_nand_gate_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_35_2_fu_102_w1_out),
    .w1_out_ap_vld(grp_nand_gate_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_35_2_fu_102_w1_out_ap_vld),
    .w2_out(grp_nand_gate_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_35_2_fu_102_w2_out),
    .w2_out_ap_vld(grp_nand_gate_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_35_2_fu_102_w2_out_ap_vld),
    .bias_out(grp_nand_gate_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_35_2_fu_102_bias_out),
    .bias_out_ap_vld(grp_nand_gate_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_35_2_fu_102_bias_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_nand_gate_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_35_2_fu_102_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            grp_nand_gate_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_35_2_fu_102_ap_start_reg <= 1'b1;
        end else if ((grp_nand_gate_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_35_2_fu_102_ap_ready == 1'b1)) begin
            grp_nand_gate_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_35_2_fu_102_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_nand_gate_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_35_2_fu_102_bias_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        bias_loc_fu_50 <= grp_nand_gate_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_35_2_fu_102_bias_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_nand_gate_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_35_2_fu_102_w1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        w1_loc_fu_58 <= grp_nand_gate_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_35_2_fu_102_w1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_nand_gate_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_35_2_fu_102_w2_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        w2_loc_fu_54 <= grp_nand_gate_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_35_2_fu_102_w2_out;
    end
end

assign ap_ST_fsm_state1_blk = 1'b0;

always @ (*) begin
    if ((grp_nand_gate_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_35_2_fu_102_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_nand_gate_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_35_2_fu_102_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln63_fu_149_p2 = (bias_loc_fu_50 + and_ln63_fu_129_p2);

assign and_ln63_1_fu_143_p2 = (w2_loc_fu_54 & select_ln63_1_fu_135_p3);

assign and_ln63_fu_129_p2 = (w1_loc_fu_58 & select_ln63_fu_121_p3);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign bias_out = bias_loc_fu_50;

assign c = (tmp_fu_161_p3 ^ 1'd1);

assign grp_nand_gate_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_35_2_fu_102_ap_start = grp_nand_gate_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_35_2_fu_102_ap_start_reg;

assign select_ln63_1_fu_135_p3 = ((b[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign select_ln63_fu_121_p3 = ((a[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign tmp_fu_161_p3 = z_final_fu_155_p2[32'd7];

assign w1_out = w1_loc_fu_58;

assign w2_out = w2_loc_fu_54;

assign z_final_fu_155_p2 = (add_ln63_fu_149_p2 + and_ln63_1_fu_143_p2);

endmodule //nand_gate
